Select
    RM_Part_No,
    FG_Part_No_FG1,
    Avg_Monthly_Sales_FG1S,
    Months_On_Hand_FG1S,
    Required_Date_FG1S,
    Avg_Monthly_Forecast_FG1F,
    Months_On_Hand_FG1F,
    Required_Date_FG1F,
    FG_Part_No_FG2,
    Avg_Monthly_Sales_Fg2s,
    Months_On_Hand_FG2S,
    Avg_Monthly_Forecast_FG2F,
    Months_On_Hand_FG2F,
    Required_Date_FG2F
From
    KD_MRP