CREATE TABLE kd_quota_rep_tab AS
SELECT
                rep.rep_code AS repnumber,
                rep.rep_name,
                SUM(rep.m1_rep_quota) AS jan,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m1_rep_quota,0)) AS m1_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m1_rep_quota,0)) AS m1_bio,
                SUM(rep.m2_rep_quota) AS feb,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m2_rep_quota,0)) AS m2_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m2_rep_quota,0)) AS m2_bio,
                SUM(rep.m3_rep_quota) AS mar,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m3_rep_quota,0)) AS m3_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m3_rep_quota,0)) AS m3_bio,
                SUM(rep.m4_rep_quota) AS apr,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m4_rep_quota,0)) AS m4_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m4_rep_quota,0)) AS m4_bio,
                SUM(rep.m5_rep_quota) AS may,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m5_rep_quota,0)) AS m5_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m5_rep_quota,0)) AS m5_bio,
                SUM(rep.m6_rep_quota) AS june,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m6_rep_quota,0)) AS m6_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m6_rep_quota,0)) AS m6_bio,
                SUM(rep.m7_rep_quota) AS july,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m7_rep_quota,0)) AS m7_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m7_rep_quota,0)) AS m7_bio,
                SUM(rep.m8_rep_quota) AS aug,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m8_rep_quota,0)) AS m8_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m8_rep_quota,0)) AS m8_bio,
                SUM(rep.m9_rep_quota) AS sept,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m9_rep_quota,0)) AS m9_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m9_rep_quota,0)) AS m9_bio,
                SUM(rep.m10_rep_quota) AS oct,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m10_rep_quota,0)) AS m10_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m10_rep_quota,0)) AS m10_bio,
                SUM(rep.m11_rep_quota) AS nov,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m11_rep_quota,0)) AS m11_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m11_rep_quota,0)) AS m11_bio,
                SUM(rep.m12_rep_quota) AS dec,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m12_rep_quota,0)) AS m12_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m12_rep_quota,0)) AS m12_bio,
                SUM(rep.m1_rep_quota) + SUM(rep.m2_rep_quota) + SUM(rep.m3_rep_quota) AS qtr1,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m1_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m2_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m3_rep_quota,0)) AS qtr1_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m1_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m2_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m3_rep_quota,0)) AS qtr1_bio,
                SUM(rep.m4_rep_quota) + SUM(rep.m5_rep_quota) + SUM(rep.m6_rep_quota) AS qtr2,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m4_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m5_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m6_rep_quota,0)) AS qtr2_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m4_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m5_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m6_rep_quota,0)) AS qtr2_bio,
                SUM(rep.m7_rep_quota) + SUM(rep.m8_rep_quota) + SUM(rep.m9_rep_quota) AS qtr3,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m7_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m8_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m9_rep_quota,0)) AS qtr3_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m7_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m8_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m9_rep_quota,0)) AS qtr3_bio,
                SUM(rep.m10_rep_quota) + SUM(rep.m11_rep_quota) + SUM(rep.m12_rep_quota) AS qtr4,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m10_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m11_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m12_rep_quota,0)) AS qtr4_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m10_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m11_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m12_rep_quota,0)) AS qtr4_bio,
                rep.region_code AS region,
                reg.manager as regionmgr,
                SUM(rep.m1_rep_quota) + SUM(rep.m2_rep_quota) + SUM(rep.m3_rep_quota) + SUM(rep.m4_rep_quota) + SUM(rep.m5_rep_quota) + SUM(rep.m6_rep_quota) + SUM(rep.m7_rep_quota) + SUM(rep.m8_rep_quota) + SUM(rep.m9_rep_quota) + SUM(rep.m10_rep_quota) + SUM(rep.m11_rep_quota) + SUM(rep.m12_rep_quota) AS year,
                SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m1_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m2_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m3_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m4_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m5_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m6_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m7_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m8_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m9_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m10_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m11_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'IMPLANTS',rep.m12_rep_quota,0)) AS year_impl,
                SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m1_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m2_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m3_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m4_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m5_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m6_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m7_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m8_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m9_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m10_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m11_rep_quota,0)) + SUM(DECODE(UPPER(rep.product_type),'BIOMATERIALS',rep.m12_rep_quota,0)) AS year_bio 
FROM
                kd_quota_rep rep
                LEFT JOIN kd_quota_region_config reg
                    ON rep.region_code = reg.region_code
GROUP BY
                rep_code,
                rep_name,
                rep.region_code,
                reg.manager