Select
    'USA' COMPANY,
    UPPER(A.DLVCOUNTRYREGIONID) TERRITORY,
    UPPER(A.CUSTGROUP) SALESMNGR,
    A.DELIVERYNAME CUSTOMER,
    A.INVOICEACCOUNT CUSTOMERNO,
	--CONVERT(DATETIME,B.INVOICEDATE,102) As INVOICEDATE,
	B.INVOICEDATE,
	A.INVOICEID INVOICENO,
	'' FAMILY,
	D.NAME As GROUPID,
	B.NAME ITEM,
	B.ITEMID ITEMNO,
	SUM(B.LINEAMOUNT) As AMT,
	SUM(B.QTY) QTY,
	CONVERT(INT, B.LINENUM) As LINE_ITEM_NO,
    B.RECID,
	A.SALESID
From
    Paltop_ax09_Live_db.dbo.CUSTINVOICEJOUR  A Left Join Paltop_ax09_Live_db.dbo.CUSTINVOICETRANS B On 
		A.INVOICEID = B.INVOICEID And
		A.DATAAREAID = B.DATAAREAID
											   Left Join Paltop_ax09_Live_db.dbo.INVENTTABLE C On
		B.ITEMID = C.ITEMID And
		C.DATAAREAID = 'virt'
											   Left Join Paltop_ax09_Live_db.dbo.INVENTITEMGROUP D On
											   
		C.ITEMGROUPID = D.ITEMGROUPID And
		D.DATAAREAID = 'virt'
Where
	A.DATAAREAID = 'usa' And
	A.INVOICEDATE >= CONVERT(DateTime,'2019-01-01',102) And
	A.CUSTGROUP != '90' 
Group By
	UPPER(A.DLVCOUNTRYREGIONID),
	UPPER(A.CUSTGROUP),
	A.DELIVERYNAME,
	A.INVOICEACCOUNT,
	--CONVERT(DATETIME,B.INVOICEDATE,102),
	B.INVOICEDATE,
	A.INVOICEID,
	D.NAME,
	A.CUSTGROUP,
	B.NAME,
	B.ITEMID,
	B.LINENUM,
	B.RECID,
	A.SALESID
Having
    SUM(B.QTY) != 0