--------------------------------------------------------
--  DDL for Table KD_MRP_PART_RELATIONSHIPS
--------------------------------------------------------

  CREATE TABLE "IFSAPP"."KD_MRP_PART_RELATIONSHIPS" 
   (	"RM_PART_NO" VARCHAR2(4000 BYTE), 
	"PROC_PART_NO" VARCHAR2(4000 BYTE), 
	"FG_PART_NO" VARCHAR2(4000 BYTE), 
	"FG_PART_INDEX" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IFSAPP_DATA" ;
