Create Or Replace View KD_ASP_5Q As
Select
    A.Region_Code,
    A.Salesman_Code,
    Person_Info_Api.Get_Name(A.Salesman_Code) As Salesman_Name,
    Nvl(A."CQ_IMPLANTS_ASP",0) As "CQ_IMPLANTS_ASP",
    Nvl(B."1PQ_IMPLANTS_ASP",0) As "1PQ_IMPLANTS_ASP",
    Nvl(C."2PQ_IMPLANTS_ASP",0) As "2PQ_IMPLANTS_ASP",
    Nvl(D."3PQ_IMPLANTS_ASP",0) As "3PQ_IMPLANTS_ASP",
    Nvl(E."4PQ_IMPLANTS_ASP",0) As "4PQ_IMPLANTS_ASP",
    Nvl(A."CQ_IMPLANT_BODIES_ASP",0) As "CQ_IMPLANT_BODIES_ASP",
    Nvl(B."1PQ_IMPLANT_BODIES_ASP",0) As "1PQ_IMPLANT_BODIES_ASP",
    Nvl(C."2PQ_IMPLANT_BODIES_ASP",0) As "2PQ_IMPLANT_BODIES_ASP",
    Nvl(D."3PQ_IMPLANT_BODIES_ASP",0) As "3PQ_IMPLANT_BODIES_ASP",
    Nvl(E."4PQ_IMPLANT_BODIES_ASP",0) As "4PQ_IMPLANT_BODIES_ASP",
    Nvl(A."CQ_PRIMA_ASP",0) As "CQ_PRIMA_ASP",
    Nvl(B."1PQ_PRIMA_ASP",0) As "1PQ_PRIMA_ASP",
    Nvl(C."2PQ_PRIMA_ASP",0) As "2PQ_PRIMA_ASP",
    Nvl(D."3PQ_PRIMA_ASP",0) As "3PQ_PRIMA_ASP",
    Nvl(E."4PQ_PRIMA_ASP",0) As "4PQ_PRIMA_ASP",
    Nvl(A."CQ_PRMA+_ASP",0) As "CQ_PRMA+_ASP",
    Nvl(B."1PQ_PRMA+_ASP",0) As "1PQ_PRMA+_ASP",
    Nvl(C."2PQ_PRMA+_ASP",0) As "2PQ_PRMA+_ASP",
    Nvl(D."3PQ_PRMA+_ASP",0) As "3PQ_PRMA+_ASP",
    Nvl(E."4PQ_PRMA+_ASP",0) As "4PQ_PRMA+_ASP",
    Nvl(A."CQ_GNSIS_ASP",0) As "CQ_GNSIS_ASP",
    Nvl(B."1PQ_GNSIS_ASP",0) As "1PQ_GNSIS_ASP",
    Nvl(C."2PQ_GNSIS_ASP",0) As "2PQ_GNSIS_ASP",
    Nvl(D."3PQ_GNSIS_ASP",0) As "3PQ_GNSIS_ASP",
    Nvl(E."4PQ_GNSIS_ASP",0) As "4PQ_GNSIS_ASP",
    Nvl(A."CQ_TLMAX_ASP",0) As "CQ_TLMAX_ASP",
    Nvl(B."1PQ_TLMAX_ASP",0) As "1PQ_TLMAX_ASP",
    Nvl(C."2PQ_TLMAX_ASP",0) As "2PQ_TLMAX_ASP",
    Nvl(D."3PQ_TLMAX_ASP",0) As "3PQ_TLMAX_ASP",
    Nvl(E."4PQ_TLMAX_ASP",0) As "4PQ_TLMAX_ASP",
    Nvl(A."CQ_PCOMM_ASP",0) As "CQ_PCOMM_ASP",
    Nvl(B."1PQ_PCOMM_ASP",0) As "1PQ_PCOMM_ASP",
    Nvl(C."2PQ_PCOMM_ASP",0) As "2PQ_PCOMM_ASP",
    Nvl(D."3PQ_PCOMM_ASP",0) As "3PQ_PCOMM_ASP",
    Nvl(E."4PQ_PCOMM_ASP",0) As "4PQ_PCOMM_ASP",
    Nvl(A."CQ_COMM_ASP",0) As "CQ_COMM_ASP",
    Nvl(B."1PQ_COMM_ASP",0) As "1PQ_COMM_ASP",
    Nvl(C."2PQ_COMM_ASP",0) As "2PQ_COMM_ASP",
    Nvl(D."3PQ_COMM_ASP",0) As "3PQ_COMM_ASP",
    Nvl(E."4PQ_COMM_ASP",0) As "4PQ_COMM_ASP",
    Nvl(A."CQ_BIO_ASP",0) As "CQ_BIO_ASP",
    Nvl(B."1PQ_BIO_ASP",0) As "1PQ_BIO_ASP",
    Nvl(C."2PQ_BIO_ASP",0) As "2PQ_BIO_ASP",
    Nvl(D."3PQ_BIO_ASP",0) As "3PQ_BIO_ASP",
    Nvl(E."4PQ_BIO_ASP",0) As "4PQ_BIO_ASP",
    Nvl(A."CQ_BVINE_ASP",0) As "CQ_BVINE_ASP",
    Nvl(B."1PQ_BVINE_ASP",0) As "1PQ_BVINE_ASP",
    Nvl(C."2PQ_BVINE_ASP",0) As "2PQ_BVINE_ASP",
    Nvl(D."3PQ_BVINE_ASP",0) As "3PQ_BVINE_ASP",
    Nvl(E."4PQ_BVINE_ASP",0) As "4PQ_BVINE_ASP",
    Nvl(A."CQ_CONNX_ASP",0) As "CQ_CONNX_ASP",
    Nvl(B."1PQ_CONNX_ASP",0) As "1PQ_CONNX_ASP",
    Nvl(C."2PQ_CONNX_ASP",0) As "2PQ_CONNX_ASP",
    Nvl(D."3PQ_CONNX_ASP",0) As "3PQ_CONNX_ASP",
    Nvl(E."4PQ_CONNX_ASP",0) As "4PQ_CONNX_ASP",
    Nvl(A."CQ_CYTOP_ASP",0) As "CQ_CYTOP_ASP",
    Nvl(B."1PQ_CYTOP_ASP",0) As "1PQ_CYTOP_ASP",
    Nvl(C."2PQ_CYTOP_ASP",0) As "2PQ_CYTOP_ASP",
    Nvl(D."3PQ_CYTOP_ASP",0) As "3PQ_CYTOP_ASP",
    Nvl(E."4PQ_CYTOP_ASP",0) As "4PQ_CYTOP_ASP",
    Nvl(A."CQ_DYNAB_ASP",0) As "CQ_DYNAB_ASP",
    Nvl(B."1PQ_DYNAB_ASP",0) As "1PQ_DYNAB_ASP",
    Nvl(C."2PQ_DYNAB_ASP",0) As "2PQ_DYNAB_ASP",
    Nvl(D."3PQ_DYNAB_ASP",0) As "3PQ_DYNAB_ASP",
    Nvl(E."4PQ_DYNAB_ASP",0) As "4PQ_DYNAB_ASP",
    Nvl(A."CQ_DYNAG_ASP",0) As "CQ_DYNAG_ASP",
    Nvl(B."1PQ_DYNAG_ASP",0) As "1PQ_DYNAG_ASP",
    Nvl(C."2PQ_DYNAG_ASP",0) As "2PQ_DYNAG_ASP",
    Nvl(D."3PQ_DYNAG_ASP",0) As "3PQ_DYNAG_ASP",
    Nvl(E."4PQ_DYNAG_ASP",0) As "4PQ_DYNAG_ASP",
    Nvl(A."CQ_DYNAM_ASP",0) As "CQ_DYNAM_ASP",
    Nvl(B."1PQ_DYNAM_ASP",0) As "1PQ_DYNAM_ASP",
    Nvl(C."2PQ_DYNAM_ASP",0) As "2PQ_DYNAM_ASP",
    Nvl(D."3PQ_DYNAM_ASP",0) As "3PQ_DYNAM_ASP",
    Nvl(E."4PQ_DYNAM_ASP",0) As "4PQ_DYNAM_ASP",
    Nvl(A."CQ_SYNTH_ASP",0) As "CQ_SYNTH_ASP",
    Nvl(B."1PQ_SYNTH_ASP",0) As "1PQ_SYNTH_ASP",
    Nvl(C."2PQ_SYNTH_ASP",0) As "2PQ_SYNTH_ASP",
    Nvl(D."3PQ_SYNTH_ASP",0) As "3PQ_SYNTH_ASP",
    Nvl(E."4PQ_SYNTH_ASP",0) As "4PQ_SYNTH_ASP",
    Nvl(A."CQ_MTF_ASP",0) As "CQ_MTF_ASP",
    Nvl(B."1PQ_MTF_ASP",0) As "1PQ_MTF_ASP",
    Nvl(C."2PQ_MTF_ASP",0) As "2PQ_MTF_ASP",
    Nvl(D."3PQ_MTF_ASP",0) As "3PQ_MTF_ASP",
    Nvl(E."4PQ_MTF_ASP",0) As "4PQ_MTF_ASP"
From
    Kd_Asp_Cq_Tab A,
    Kd_Asp_1pq_Tab B,
    Kd_Asp_2pq_Tab C,
    Kd_Asp_3pq_Tab D,
    Kd_Asp_4pq_Tab E
Where
    (A.Salesman_Code = B.Salesman_Code And B.Salesman_Code = C.Salesman_Code and C.Salesman_Code = D.Salesman_Code and D.Salesman_Code = E.Salesman_Code and A.Region_Code = B.Region_Code and B.REgion_Code = C.Region_Code and C.Region_Code = D.REgion_Code and D.REgion_Code = E.Region_Code) OR
    (A.Salesman_Code Is Null and B.Salesman_Code IS Null and C.Salesman_Code Is Null and D.Salesman_Code Is Null and E.Salesman_Code Is Null and A.Region_Code = B.Region_Code and B.REgion_Code = C.Region_Code and C.Region_Code = D.REgion_Code and D.REgion_Code = E.Region_Code) OR
    (A.Salesman_Code Is Null and B.Salesman_Code IS Null and C.Salesman_Code Is Null and D.Salesman_Code Is Null and E.Salesman_Code Is Null and A.Region_Code Is Null and B.Region_Code Is Null and C.Region_Code Is Null and D.REgion_Code Is Null and E.Region_Code Is Null)
Order By
    Decode(A.Region_Code,'USEC',1,'USCE',2,'USWC',3,'SECA',4,'UNASSIGNED',5),
    A.Salesman_Code