Create or Replace View KD_Boomi_Svq As
Select
  Rank() Over (Order By A.YTD_Quota_Pct Desc) as Rank,
  To_Char(Sysdate,'YYYY-MM-DD') "Current_DATE",
  A.Salesman_Code,
  A.Name,
  A.Region,
  Round(A.Today) As Today,
  Round(A.This_Month) As This_Month,
  Round(A.This_Month_Implants) As This_Month_Implants,
  Round(A.This_Month_Bio) As This_Month_Bio,
  A.MTD_Quota,
  A.MTD_Quota_Impl,
  A.MTD_Quota_Bio,
  A.MTD_Quota_Remaining,
  A.MTD_Quota_Impl_Remaining,
  A.MTD_Quota_Bio_Remaining,
  A.Month_Quota_Pct,
  A.Month_Quota_Pct_Impl,
  A.Month_Quota_Pct_Bio,
  A.Mtd_Quota_Pct,
  A.MTD_Quota_Pct_Impl,
  A.MTD_Quota_Pct_Bio,
  Round(A.Month_Remaining) As Month_Remaining,
  Round(A.Month_Remaining_Impl) as Month_Remaining_Impl,
  Round(A.Month_Remaining_Bio) As Month_Remaining_Bio,
  Round(B.Month_Quota) As Month_Quota,
  Round(B.Month_Quota_Impl) As Month_Quota_Impl,
  Round(B.Month_Quota_Bio) As Month_Quota_Bio,
  Round(A.Month_Remaining / Nullif((C.Total_Sales_Days - C.Elapsed_Work_Days),0)) As Avg_Per_Day_Req_Month,
  Case When Round(((B.Month_Quota / C.Total_Sales_Days) * C.Elapsed_Work_Days) - A.This_Month) > 0 
       Then Round(((B.Month_Quota / C.Total_Sales_Days) * C.Elapsed_Work_Days) - A.This_Month)
       Else 0
  End As "SALES_TODAY_TO_HIT_100%_MTD",
  Round(A.This_Quarter) As This_Quarter,
  Round(A.This_Quarter_Implants) As This_Quarter_Implants,
  Round(A.This_Quarter_Bio) As This_Quarter_Bio,
  Round(D.Qtr_Quota) As Qtr_Quota,
  Round(D.Qtr_Quota_Impl) As Qtr_Quota_Impl,
  Round(D.Qtr_Quota_Bio) As Qtr_Quota_Bio,
  A.Quarter_Quota_Pct,
  A.Quarter_Quota_Pct_Impl,
  A.Quarter_Quota_Pct_Bio,
  A.Qtd_Quota_Pct,
  A.Qtd_Quota_Pct_Impl,
  A.Qtd_Quota_Pct_Bio,
  Round(A.Quarter_Remaining) As Quarter_Remaining,
  Round(A.Quarter_Remaining_Impl) As Quarter_Remaining_Impl,
  Round(A.Quarter_Remaining_Bio) As Quarter_Remaining_Bio,
  Round(A.This_Year) As This_Year,
  Round(A.This_Year_Implants) As This_Year_Implants,
  Round(A.This_Year_Bio) As This_Year_Bio,
  Round(E.Year_Quota) As Year_Quota,
  Round(E.Year_Quota_Impl) As Year_Quota_Impl,
  Round(E.Year_Quota_Bio) As Year_Quota_Bio,
  A.Year_Quota_Pct,
  A.Year_Quota_Pct_Impl,
  A.YEar_Quota_Pct_Bio,
  A.Ytd_Quota_Pct,
  A.YTD_Quota_Pct_Impl,
  A.YTD_Quota_Pct_Bio,
  A.YTD_Quota,
  A.YTD_Quota_Impl,
  A.YTD_Quota_Bio,
  Round(A.Year_Remaining) As Year_Remaining,
  A.YTD_Quota_Remaining,
  Round(A.Year_Remaining_Impl) As Year_Remaining_Impl,
  A.YTD_Quota_Impl_Remaining,
  Round(A.YEar_Remaining_Bio) As Year_Remaining_Bio,
  A.YTD_Quota_Bio_Remaining,
  A.Year_Quota_Pct_Reg,
  A.year_Quota_Pct_Impl_Reg,
  A.Year_Quota_Pct_Bio_Reg,
  A.YTD_Quota_PCT_REG,
  A.YTD_Quota_Pct_Impl_Reg,
  A.YTD_Quota_Pct_Bio_Reg,
  A.Quarter_Quota_Pct_Reg,
  A.Quarter_Quota_Pct_Impl_Reg,
  A.Quarter_Quota_Pct_Bio_Reg,
  A.Qtd_Quota_Pct_Reg,
  A.Qtd_Quota_Pct_Impl_Reg,
  A.Qtd_Quota_Pct_Bio_Reg,
  A.Month_Quota_Pct_Reg,
  A.Month_Quota_Pct_Impl_Reg,
  A.Month_Quota_Pct_Bio_Reg,
  A.MTD_Quota_PCT_REG,
  A.MTD_Quota_Pct_Impl_Reg,
  A.MTD_Quota_Pct_Bio_Reg,
  A.Year_Quota_Pct_Total,
  A.Year_Quota_Pct_Impl_Total,
  A.Year_Quota_Pct_Bio_Total,
  A.YTD_Quota_Pct_Total,
  A.YTD_Quota_Pct_Impl_Total,
  A.YTD_Quota_Pct_Bio_Total,
  A.Quarter_Quota_Pct_Total,
  A.Quarter_Quota_Pct_Impl_Total,
  A.Quarter_Quota_Pct_Bio_Total,
  A.Qtd_Quota_Pct_Total,
  A.Qtd_Quota_Pct_Impl_Total,
  A.Qtd_Quota_Pct_Bio_Total,
  A.Month_Quota_Pct_Total,
  A.Month_Quota_Pct_Impl_Total,
  A.Month_Quota_Pct_Bio_Total,
  A.Mtd_Quota_Pct_Total,
  A.MTD_Quota_Pct_Impl_Total,
  A.MTD_Quota_pct_Bio_Total,
  A.PYMTD_SD,
  A.PYQTD_SD,
  A.PYYTD_SD,
  A.PY_MTD_SD_REG,
  A.PY_QTD_SD_REG,
  A.PY_YTD_SD_REG,
  A.PY_Month_SD_Total,
  A.PY_Quarter_SD_Total,
  A.PY_Year_SD_Total,
  C.Total_Sales_Days - C.Elapsed_Work_Days As Sales_Days_Remaining_Month,
  Round(G.This_Month) As This_Month_Reg,
  Round(G.This_Month_Implants) As This_Month_Impl_Reg,
  Round(G.This_Month_Bio) As This_Month_Bio_Reg,
  Round(G.Month_Quota) As Month_Quota_Reg,
  Round(G.Month_Quota_Impl) As Month_Quota_Impl_Reg,
  Round(G.Month_Quota_Bio) As Month_Quota_Bio_Reg,
  Round(G.Month_Quota - G.This_Month) As Month_Remaining_Reg,
  Round(G.Month_Quota_Impl - G.This_Month_Implants) As Month_Remaining_Impl_Reg,
  Round(G.Month_Quota_Bio - G.This_Month_Bio) As Month_Remaining_Bio_Reg,
  Round(H.This_Quarter) As This_Quarter_Reg,
  Round(H.This_Quarter_Implants) As This_Quarter_Impl_Reg,
  Round(H.This_Quarter_Bio) As This_Quarter_Bio_Reg
From
  Kd_Svq A
  LEFT JOIN kd_Svq_This_Month B
    ON A.Salesman_Code = B.Salesman_Code
  LEFT JOIN Kd_Svq_This_Quarter D
    ON A.Salesman_Code = D.Salesman_Code
  LEFT JOIN Kd_Svq_This_Year E
    ON A.Salesman_Code = E.Salesman_Code
  LEFT JOIN KD_Svq_Margins I
    ON A.Salesman_Code = I.Salesman_Code,
  Kd_Monthly_Calendar C,
  Kd_Svq_This_Month_Reg G,
  Kd_Svq_This_Quarter_Reg H

Where
  C.Month = Extract(Month From Sysdate) And
  A.Region = G.Region And
  A.Region = H.Region And 
  A.Salesman_Code != '999'