Create Or Replace View KD_PT_Sales_Data As 
Select
    '100' As Site,
    A.Invoiceno as Invoice_ID,
    A.Line_Item_No As Item_ID,
    To_Date(A.InvoiceDate,'MM/DD/YYYY') As InvoiceDate,
    A.Qty As Invoiced_Qty,
    A.Amt/A.Qty As Sale_Unit_Price,
    0 as Discount,
    0 As Net_Curr_Amount,
    0 As Gross_Curr_Amount,
    Case When A.ItemNo = '97-00001' Then 'PTUSA Freight' Else Sales_Part_Api.Get_Catalog_Desc('100',A.ItemNo) End As Catalog_Desc,
    Customer_Info_Api.Get_Name(B.KD_Cust_ID) As Customer_Name,
    'P' || SubStr(A.Invoiceno,3,7) As Order_No,
    B.KD_Cust_ID As Customer_No,
    Cust_Ord_Customer_Api.Get_Cust_Grp(B.KD_Cust_ID) As Cust_Grp,
    Decode(A.ItemNo,'97-00001','PTFREIGHT',A.ItemNo) As Catalog_No,
    'PTUSA' as Authorize_Code,
    Cust_Ord_Customer_Api.Get_Salesman_Code(B.KD_Cust_ID) As Salesman_Code,
    C.Commission_Receiver As Commission_Receiver,
    Cust_Ord_Customer_Address_Api.Get_District_Code(B.KD_Cust_ID,99) As District_Code,
    Cust_Ord_Customer_Address_Api.Get_Region_Code(B.KD_Cust_ID,99) As Region_Code,
    To_Date(A.InvoiceDate,'MM/DD/YYYY') As CreateDate,
    Inventory_Part_Api.Get_Part_Product_Code('100',A.ItemNo) as Part_Product_Code,
    Inventory_Part_Api.Get_Part_Product_Family('100',A.ItemNo) as Part_Product_Family,
    Inventory_Part_Api.Get_Second_Commodity('100',A.ItemNo) As Second_Commodity,
    InitCap(To_Char(To_Date(A.InvoiceDate,'MM/DD/YYYY'),'MONTH')) As InvoiceMonth,
    'QTR' || To_Char(To_Date(A.InvoiceDate,'MM/DD/YYYY'),'Q') As InvoiceQtr,
    'QTR' || To_Char(To_Date(A.InvoiceDate,'MM/DD/YYYY'),'Q') || '/' || To_Char(To_Date(A.InvoiceDate,'MM/DD/YYYY'),'YYYY') As InvoiceQtrYr,
    To_Char(To_Date(A.InvoiceDate,'MM/DD/YYYY'),'MM/YYYY') As InvoiceMthYr,
    '0' as GroupID,
    Case When A.ItemNo = '97-00001' Then 'Freight' Else 'Target' End as Type_Designation,
    B.KD_Cust_ID As Customer_No_Pay,
    Case When A.ItemNo = '97-00001' Then 'Freight' Else KD_Get_Corporate_Form(B.KD_Cust_ID) End As Corporate_Form,
    Amt As FixedAmounts,
    Amt As AllAmounts,
    Amt As LocalAmount,
    Amt As TrueLocalAmt,
    0 As Vat_Dom_Amount,
    Null Vat_Code,
    Inventory_Part_Cost_Api.Get_Part_Cost('100',A.Itemno) As "COST",
    Case When A.ItemNo = '97-00001' Then 'Freight' When Sales_Part_Api.Get_Catalog_Desc('100',A.ItemNo)Is Null Then Null Else 'Parts' End As Charge_Type,
    'PTUSAXLSX' As Source,
    Case When A.ItemNo = '97-00001' Then 'Market' Else Null End As Market_Code,
    Customer_Info_Api.Get_Association_No(B.KD_Cust_ID) As Association_No,
    0 As Vat_Curr_Amount,
    Null as Pay_Term_Description,
    Decode(A.ItemNo,'97-00001',Null,'PTUSA') As KD_Reference,
    Decode(A.ItemNo,'97-00001',Null,'PTUSA') As CustomerRef,
    Null As Delivery_Date,
    Null As Ship_Via,
    B.KD_Cust_ID As Delivery_Identity,
    B.KD_Cust_ID as Identity,
    '99' As Delivery_Address_ID,
    '99' As Invoice_Address_ID,
    'USD' As Currency,
    Null As RMA_No,
    Customer_Info_Address_Api.Get_Address1(B.KD_Cust_ID,'99') As InvoiceAdd1,
    Customer_Info_Address_Api.Get_Address2(B.KD_Cust_ID,'99') As InvoiceAdd2,
    Customer_Info_Address_Api.Get_City(B.KD_Cust_ID,'99') As InvoiceCity,
    Customer_Info_Address_Api.Get_State(B.KD_Cust_ID,'99') As InvoiceState,
    Customer_Info_Address_Api.Get_Zip_Code(B.KD_Cust_ID,'99') As InvoiceZip,
    Customer_Info_Address_Api.Get_country(B.KD_Cust_ID,'99') As InvoiceCoutry,
    Customer_Info_Address_Api.Get_County(B.KD_Cust_ID,'99') As InvoiceCounty,
    Customer_Info_Address_Api.Get_Address1(B.KD_Cust_ID,'99') As DelivAdd1,
    Customer_Info_Address_Api.Get_Address2(B.KD_Cust_ID,'99') As DelivAdd2,
    Customer_Info_Address_Api.Get_City(B.KD_Cust_ID,'99') As DelivCity,
    Customer_Info_Address_Api.Get_State(B.KD_Cust_ID,'99') As DelivState,
    Customer_Info_Address_Api.Get_Zip_Code(B.KD_Cust_ID,'99') As DelivZip,
    Customer_Info_Address_Api.Get_country(B.KD_Cust_ID,'99') As DelivCoutry,
    Customer_Info_Address_Api.Get_County(B.KD_Cust_ID,'99') As DelivCounty
From
    KD_PT_Raw_Data A Left Join KD_PT_Cust_Map B
        On A.CustomerNo = B.PT_Cust_ID
                     Left Join Cust_Def_Com_Receiver C 
        On B.KD_Cust_ID = C.Customer_No
Where
    A.CustomerNo != 'Cust1002656' And
    A.ItemNo Not In ('30-90054','97-90100','97-90000','85-70023','30-90004')