Create or Replace View srrepquota As 
Select 
    Territory_Number as RepNumber,
    Rep_Name,
    Sum(M1) As Jan,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M1 Else 0 End) As M1_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M1 Else 0 End) As M1_BIO,
    Sum(M2) As Feb,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M2 Else 0 End) As M2_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M2 Else 0 End) As M2_BIO,
    Sum(M3) As Mar,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M3 Else 0 End) As M3_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M3 Else 0 End) As M3_BIO,
    Sum(M4) As Apr,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M4 Else 0 End) As M4_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M4 Else 0 End) As M4_BIO,
    Sum(M5) As May,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M5 Else 0 End) As M5_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M5 Else 0 End) As M5_BIO,
    Sum(M6) As June,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M6 Else 0 End) As M6_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M6 Else 0 End) As M6_BIO,
    Sum(M7) As July,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M7 Else 0 End) As M7_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M7 Else 0 End) As M7_BIO,
    Sum(M8) As Aug,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M8 Else 0 End) As M8_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M8 Else 0 End) As M8_BIO,
    Sum(M9) As Sept,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M9 Else 0 End) As M9_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M9 Else 0 End) As M9_BIO,
    Sum(M10) As Oct,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M10 Else 0 End) As M10_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M10 Else 0 End) As M10_BIO,
    Sum(M11) As Nov,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M11 Else 0 End) As M11_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M11 Else 0 End) As M11_BIO,
    Sum(M12) As Dec,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M12 Else 0 End) As M12_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M12 Else 0 End) As M12_BIO,
    Sum(M1 + M2 + M3) As QTR1,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M1 + M2 + M3 Else 0 End) As QTR1_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M1 + M2 + M3 Else 0 End) As QTR1_BIO,
    Sum(M4 + M5 + M6) As QTR2,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M4 + M5 + M6 Else 0 End) As QTR2_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M4 + M5 + M6 Else 0 End) As QTR2_BIO,
    Sum(M7 + M8 + M9) As QTR3,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M7 + M8 + M9 Else 0 End) As QTR3_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M7 + M8 + M9 Else 0 End) As QTR3_BIO,
    Sum(M10 + M11 + M12) As QTR4,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M10 + M11 + M12 Else 0 End) As QTR4_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M10 + M11 + M12 Else 0 End) As QTR4_BIO,
    Region,
    Decode(Region,'USSC','Chris Johnson','USEC','Christian Villarroel','USNC','Michael Braun','USWC','RM USWC','UNASSIGNED','Brian Bashaw',Null) As Regionmgr,
    Sum(M1+ M2 + M3 + M4 + M5 + M6 + M7 + M8 + M9 + M10 + M11 + M12) As Year,
    Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M1 + M2 + M3 + M4 + M5 + M6 + M7 + M8 + M9 + M10 + M11 + M12 Else 0 End) As Year_IMPL,
    Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M1 + M2 + M3 + M4 + M5 + M6 + M7 + M8 +M9 + M10 + M11 + M12 Else 0 End) As Year_BIO
From
    KD_Rep_Quotas
Group By
    Territory_Number,
    Rep_Name,
    Region,
    Decode(Region,'USSC','Chris Johnson','USEC','Christian Villarroel','USNC','Michael Braun','USWC','RM USWC','UNASSIGNED','Brian Bashaw',Null)