Create or Replace View srrepquota As 
Select 
    repnumber as RepNumber,
    person_info_api.get_name(repnumber) AS Rep_Name,
    jan As Jan,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M1 Else 0 End)*/ NULL As M1_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M1 Else 0 End)*/ NULL As M1_BIO,
    feb As Feb,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M2 Else 0 End)*/ NULL As M2_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M2 Else 0 End)*/ NULL As M2_BIO,
    mar As Mar,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M3 Else 0 End)*/ NULL As M3_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M3 Else 0 End)*/ NULL As M3_BIO,
    apr As Apr,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M4 Else 0 End)*/ NULL As M4_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M4 Else 0 End)*/ NULL As M4_BIO,
    may As May,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M5 Else 0 End)*/ NULL As M5_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M5 Else 0 End)*/ NULL As M5_BIO,
    june As June,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M6 Else 0 End)*/ NULL As M6_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M6 Else 0 End)*/ NULL As M6_BIO,
    july As July,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M7 Else 0 End)*/ NULL As M7_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M7 Else 0 End)*/ NULL As M7_BIO,
    aug As Aug,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M8 Else 0 End)*/ NULL As M8_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M8 Else 0 End)*/ NULL As M8_BIO,
    sept As Sept,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M9 Else 0 End)*/ NULL As M9_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M9 Else 0 End)*/ NULL As M9_BIO,
    oct As Oct,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M10 Else 0 End)*/ NULL As M10_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M10 Else 0 End)*/ NULL As M10_BIO,
    nov As Nov,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M11 Else 0 End) */ NULL As M11_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M11 Else 0 End)*/ NULL As M11_BIO,
    dec As Dec,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M12 Else 0 End) As M12_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M12 Else 0 End) As M12_BIO,
    Sum(jan + feb + mar) As QTR1,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M1 + M2 + M3 Else 0 End)*/ NULL As QTR1_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M1 + M2 + M3 Else 0 End)*/ NULL As QTR1_BIO,
    Sum(apr + may + june) As QTR2,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M4 + M5 + M6 Else 0 End)*/ NULL As QTR2_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M4 + M5 + M6 Else 0 End)*/ NULL As QTR2_BIO,
    Sum(july + aug + sept) As QTR3,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M7 + M8 + M9 Else 0 End)*/ NULL As QTR3_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M7 + M8 + M9 Else 0 End)*/ NULL As QTR3_BIO,
    Sum(oct + nov + dec) As QTR4,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M10 + M11 + M12 Else 0 End)*/ NULL As QTR4_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M10 + M11 + M12 Else 0 End)*/ NULL As QTR4_BIO,
    Region,
    Decode(Region,'USSC','Chris Johnson','USEC','Christian Villarroel','USWC','Dan Horchover','UNASSIGNED','Mike Vandenkolk',Null) As Regionmgr,
    Sum(jan + feb + mar + apr + may + june + july + aug + sept + oct + nov + dec) As Year,
    /*Sum(Case When Upper(Product_Type) = 'IMPLANTS' Then M1 + M2 + M3 + M4 + M5 + M6 + M7 + M8 + M9 + M10 + M11 + M12 Else 0 End)*/ NULL As Year_IMPL,
    /*Sum(Case When Upper(Product_Type) = 'BIOMATERIALS' Then M1 + M2 + M3 + M4 + M5 + M6 + M7 + M8 +M9 + M10 + M11 + M12 Else 0 End)*/ NULL As Year_BIO
From
    KD_SvQ2_rep_quota
Group By
    repnumber,
    --Rep_Name,
    jan,
    feb,
    mar, 
    apr,
    may,
    june,
    july,
    aug,
    sept,
    oct,
    nov,
    dec,
    Region,
    Decode(Region,'USSC','Chris Johnson','USEC','Christian Villarroel','USWC','Dan Horchover','UNASSIGNED','Mike Vandenkolk',Null)