Select
       IFSAPP.CUST_ORD_CUSTOMER.CUSTOMER_NO,
       IFSAPP.CUSTOMER_INFO.NAME,
       IFSAPP.CUSTOMER_INFO_ADDRESS.PRIMARY_CONTACT,
       IFSAPP.CUSTOMER_INFO_ADDRESS.SECONDARY_CONTACT,       
       IFSAPP.CUSTOMER_INFO_ADDRESS.ADDRESS1,
       IFSAPP.CUSTOMER_INFO_ADDRESS.ADDRESS2,
       IFSAPP.CUSTOMER_INFO_ADDRESS.CITY,
       IFSAPP.CUSTOMER_INFO_ADDRESS.STATE,
       IFSAPP.CUSTOMER_INFO_ADDRESS.ZIP_CODE,
       IFSAPP.CUSTOMER_INFO_ADDRESS.ADDRESS_ID,
       IFSAPP.CUST_ORD_CUSTOMER.CUST_GRP,
       IFSAPP.CUST_ORD_CUSTOMER.SALESMAN_CODE,
       IFSAPP.CUSTOMER_INFO.association_no,
decode(IFSAPP.CC_CUSTOMER_INFO_COMM_METHOD.method_id,'Phone',IFSAPP.CC_CUSTOMER_INFO_COMM_METHOD.VALUE) Phone,
decode(IFSAPP.CC_CUSTOMER_INFO_COMM_METHOD.method_id,'Fax',IFSAPP.CC_CUSTOMER_INFO_COMM_METHOD.VALUE) Fax
  FROM ((IFSAPP.CUST_ORD_CUSTOMER INNER JOIN IFSAPP.CUSTOMER_INFO_ADDRESS ON
        IFSAPP.CUST_ORD_CUSTOMER.CUSTOMER_NO =
        IFSAPP.CUSTOMER_INFO_ADDRESS.CUSTOMER_ID) INNER JOIN
        IFSAPP.CUSTOMER_INFO ON IFSAPP.CUSTOMER_INFO_ADDRESS.CUSTOMER_ID =
        IFSAPP.CUSTOMER_INFO.CUSTOMER_ID)
          LEFT OUTER JOIN IFSAPP.CC_CUSTOMER_INFO_COMM_METHOD ON IFSAPP.CUSTOMER_INFO_ADDRESS.CUSTOMER_ID =
                                                   IFSAPP.CC_CUSTOMER_INFO_COMM_METHOD.CUSTOMER_ID
  WHERE UPPER(IFSAPP.CUSTOMER_INFO.NAME) LIKE UPPER('&NAME') OR
        IFSAPP.CUST_ORD_CUSTOMER.CUSTOMER_NO = '&CUSTOMER_NO'   OR
        IFSAPP.CUSTOMER_INFO_ADDRESS.ZIP_CODE = '&ZIP'  OR
        UPPER(IFSAPP.CUST_ORD_CUSTOMER.salesman_code)  LIKE UPPER('&SALESMAN')  
OR
       UPPER(IFSAPP.CUSTOMER_INFO_ADDRESS.CITY) like UPPER('&CITY') OR
        UPPER(IFSAPP.CUSTOMER_INFO_ADDRESS.PRIMARY_CONTACT) LIKE UPPER('&PRIMARY_CONTACT') OR
        UPPER(IFSAPP.CUSTOMER_INFO_ADDRESS.SECONDARY_CONTACT) LIKE UPPER('&SECONDARY_CONTACT')
OR      UPPER(IFSAPP.CUSTOMER_INFO.association_no)='&ASSOC#'

order by IFSAPP.CUSTOMER_INFO.CUSTOMER_ID