create or replace PROCEDURE UPDATE_NIGHTLY IS
BEGIN
  EXECUTE IMMEDIATE 'DELETE
   FROM KD_SALES_DATA_NIGHTLY A
  WHERE A.INVOICEDATE >= TRUNC(SYSDATE - 10)
    AND A.INVOICE_ID != ''0''';
  EXECUTE IMMEDIATE 'INSERT INTO KD_SALES_DATA_NIGHTLY
      SELECT *
        FROM KD_SALES_DATA A
       WHERE A.INVOICEDATE >= TRUNC(SYSDATE - 10)
         AND NOT EXISTS (SELECT *
                           FROM KD_SALES_DATA_NIGHTLY Z
                          WHERE Z.INVOICE_ID = A.INVOICE_ID
                            AND A.ITEM_ID = Z.ITEM_ID)';
END UPDATE_NIGHTLY;
