Select
  A.*,
  (Select Max(Pay_Date) From Ledger_Transaction_Cu_Qry B Where A.Ledger_Item_Series_Id = B.Ledger_Item_Series_Id And A.Ledger_Item_Id = B.Ledger_Item_Id) As Last_Pay_Date
  
From
  Ledger_Item_Cu_Det_Qry A
Where
  Identity = '11238' And
  Open_Amount != 0;
  
SELECT
  COMPANY,
  IDENTITY,
  PARTY_TYPE,
  LEDGER_ITEM_SERIES_ID,
  LEDGER_ITEM_ID,
  LEDGER_ITEM_VERSION,
  SERIES_ID,
  PAYMENT_ID,
  TRANS_ID,
  PAYMENT_TYPE_CODE,
  PAY_DATE,
  INTEREST_DATE,
  VOUCHER_TYPE,
  VOUCHER_NO,
  VOUCHER_DATE,
  VOUCHER_PERIOD,
  CURRENCY,
  ROLLEDBACK,
  INSTALLMENT_ID,
  TICKED_OF_AMOUNT,
  DECODE(IS_NEW_LEDGER_ITEM,'FALSE', PAID_AMOUNT- NVL(BOE_DISCOUNT_FEE,0),
  PAID_AMOUNT),
  INTEREST_CURR_AMOUNT,
  FINE_CURR_AMOUNT,
  USED_DISCOUNT,
  BOE_DISCOUNT_FEE,
  CURRENCY_DIFFERENCE,
  WRITE_OFF_CURR_AMOUNT,
  WRITE_OFF_CODE,
  IFSAPP.WRITE_OFF_CODE_API.Get_Description(COMPANY,WRITE_OFF_CODE),
  DEDUCTION_CURR_AMOUNT,
  WITHHELD_TAX_CURR_AMOUNT,
  TAX_WITHH_SERIES_ID,
  TAX_WITHH_NUMBER,
  TAX_WITHH_SEQ_NO,
  TAX_CERTIFICATE_DATE,
  TAX_INVOICE_SERIES_ID,
  TAX_INVOICE_NUMBER,
  TAX_INVOICE_DATE,
  PAY_RECEIPT_ID,
  IFSAPP.PAYMENT_RECEIPT_API.Get_Pay_Receipt_Series_Id(PAY_RECEIPT_ID),
  IFSAPP.PAYMENT_RECEIPT_API.Get_Pay_Receipt_No(PAY_RECEIPT_ID),
  IFSAPP.PAYMENT_RECEIPT_API.Get_Pay_Receipt_Date(PAY_RECEIPT_ID),
  PAY_TAX_ID,
  TAX_CURR_RATE,
  BAD_DEBT_LEVEL,
  PAYMENT_ADDRESS_DATA
FROM
  IFSAPP.LEDGER_TRANSACTION_CU_QRY
WHERE
  Company                 = '100'
AND IDENTITY              = '11238'
AND PARTY_TYPE            = 'Customer'
AND LEDGER_ITEM_SERIES_ID = 'CD'
AND LEDGER_ITEM_ID        = '1001742571'
AND LEDGER_ITEM_VERSION   = 1 ;