Declare
   A_ Varchar2(32000) := Null; --p0
   B_ Varchar2(32000) := Null; --p1
   C_ Varchar2(32000) := Null; --p2
   D_ Varchar2(32000) := 'CATALOG_NO'||Chr(31)||'ABAMC17D-3'||Chr(30)||'CONTRACT'||Chr(31)||'100'||Chr(30)||'CHARACTERISTIC_CODE'||Chr(31)||'CO'||Chr(30)||'ATTR_VALUE_ALPHA'||Chr(31)||'SOMETHING'||Chr(30); --p3
   E_ Varchar2(32000) := 'DO'; --p4
Begin
  For CUR In (Select 
                A.Catalog_No
              From 
                Sales_Part A 
              Where 
                A.Catalog_No In ( 'ABAMC17D-3',
                                  'ABAMC30D-4',
                                  'ABAMCZ1',
                                  'ABAMCZ2',
                                  'ABAMCZ3',
                                  'ABAMCZ5',
                                  'ABBBMC17D-3',
                                  'ABBBMC30D-4',
                                  'ABBBMCZ1',
                                  'ABBBMCZ3',
                                  'AMC17D-3',
                                  'AMC30D-4',
                                  'AMCZ1',
                                  'AMCZ2',
                                  'AMCZ4',
                                  'AMCZ5',
                                  'AO2',
                                  'BA 10',
                                  'BA 11.5',
                                  'BA 13',
                                  'BA 8.5',
                                  'BAS1',
                                  'BAS1L',
                                  'BAT 12D-10',
                                  'BAT 12D-11.5',
                                  'BAT 12D-18',
                                  'BAT 24D-10',
                                  'BAT 24D-11.5',
                                  'BAT 24D-15',
                                  'BBBS 10',
                                  'BBBS 11.5',
                                  'BBBT 12D-10',
                                  'BBBT 12D-11.5',
                                  'BBBT 12D-13',
                                  'BBBT 12D-15',
                                  'BBBT 13',
                                  'BBBT 15',
                                  'BBBT 24D-10',
                                  'BBBT 24D-13',
                                  'BBBT 6',
                                  'BSH3',
                                  'CB75',
                                  'CBAU',
                                  'CBAU-W',
                                  'CBBB75',
                                  'CBBBU-W',
                                  'CBNU',
                                  'CBU-W',
                                  'CMAX9',
                                  'D-20T-M20',
                                  'D-29T-M15',
                                  'D-33T-M15',
                                  'D-40T-M15',
                                  'D-40TP-10',
                                  'D-40TP-11.5',
                                  'D-40TP-13',
                                  'D-40TP-15',
                                  'D-40TP-18',
                                  'D-40TP-6',
                                  'D-40TP-8.5',
                                  'D-43T-M15',
                                  'D-50TP-10',
                                  'D-50TP-11.5',
                                  'D-50TP-13',
                                  'D-50TP-15',
                                  'D-50TP-18',
                                  'D-50TP-6',
                                  'D-50TP-8.5',
                                  'D-53T-M13',
                                  'D-60TP-10',
                                  'D-60TP-11.5',
                                  'D-60TP-13',
                                  'D-60TP-15',
                                  'D-60TP-18',
                                  'D-60TP-6',
                                  'D-60TP-8.5',
                                  'DBA2',
                                  'DBA5',
                                  'DBAS24',
                                  'DBBB2',
                                  'DBBB5',
                                  'DBS24',
                                  'D-CB-F',
                                  'DN2',
                                  'D-TAP-IBS',
                                  'GC-EX-40',
                                  'GC-EX-60',
                                  'GC-NX-34',
                                  'GC-NX-40',
                                  'GC-NX-50',
                                  'GC-NX-60',
                                  'GC-NX-70',
                                  'GMC1',
                                  'GSIT2',
                                  'GSQ2',
                                  'GSQZ2',
                                  'GSU3',
                                  'GSUZ3',
                                  'GSUZ9',
                                  'I-AD',
                                  'I-BAM-62',
                                  'I-BAM-77',
                                  'I-BD-M',
                                  'I-BM-57',
                                  'IBN 10',
                                  'IBN 11.5',
                                  'IBN 13',
                                  'IBN 15',
                                  'IBN 8.5',
                                  'IBS 11.5',
                                  'IBT 13',
                                  'IBT 18',
                                  'I-CON-X',
                                  'I-DI-24D',
                                  'I-FME-XL',
                                  'I-HAD',
                                  'I-HBDM',
                                  'I-HD-L',
                                  'I-HD-LH',
                                  'I-HD-M',
                                  'I-HD-S',
                                  'I-HHD-09',
                                  'I-HHD-22S',
                                  'I-HQD-L',
                                  'I-HQD-M',
                                  'I-QDI-S',
                                  'I-WI-09',
                                  'I-WI-A',
                                  'I-WI-BM',
                                  'I-WI-QM',
                                  'I-WI-QS',
                                  'LMAX9',
                                  'LSDBAN4',
                                  'LSDBN4',
                                  'LSN12',
                                  'LT7/20',
                                  'MAX-7-11',
                                  'MAX-7-7',
                                  'MAX-7-9',
                                  'MAX-8-11',
                                  'MAX-8-7',
                                  'MAX-9-11',
                                  'MAX-9-7',
                                  'MAX-9-9',
                                  'PC2',
                                  'P-CAP-55',
                                  'SB16',
                                  'SB16PH',
                                  'SB17P',
                                  'SB-17-TT',
                                  'SBA1',
                                  'SBA16',
                                  'SBA16PH',
                                  'SBA17P',
                                  'SBA-17-TT',
                                  'SBBB16',
                                  'SBBB16PH',
                                  'SBBB17P',
                                  'SBBB-17-TT',
                                  'SBN1',
                                  'SBN5',
                                  'SC4',
                                  'SC7',
                                  'SCAU5',
                                  'SCNU2',
                                  'TB2',
                                  'TB9MAX-4',
                                  'TB9MAX-7',
                                  'TBA4',
                                  'TBA6',
                                  'TBBB2',
                                  'TCBA1H',
                                  'TCBA1NH',
                                  'TCBBB1NH',
                                  'TCBN1H',
                                  'TCBN1NH',
                                  'Total ',
                                  'TSH2',
                                  'TSHZ2',
                                  'TSHZ3',
                                  'TSU2',
                                  'TSU9',
                                  'TSUZ9',
                                  'WBA2',
                                  'WBA3',
                                  'WBA4',
                                  'WBA6',
                                  'WBBB2',
                                  'WBBB3',
                                  'WBBB4',
                                  'WBBB6',
                                  'WBN2',
                                  'WBN4',
                                  'WP-GC-S3',
                                  'ZYG-55-55N',
                                  'ZYG-55-60N',
                                  'ZYG-TR-55-35',
                                  'ZYG-TR-55-45',
                                  'ZYG-TR-55-52.5'))
  Loop
    A_  := Null; --p0
    B_  := Null; --p1
    C_  := Null; --p2
    D_  := 'CATALOG_NO'||Chr(31)||Cur.Catalog_No||Chr(30)||'CONTRACT'||Chr(31)||'100'||Chr(30)||'CHARACTERISTIC_CODE'||Chr(31)||'ZA'||Chr(30)||'ATTR_VALUE_ALPHA'||Chr(31)||'OVERRIDE'||Chr(30); --p3
    E_  := 'DO'; --p4
    Ifsapp.Sales_Part_Characteristic_Api.New__( A_ , B_ , C_ , D_ , E_ );
  End Loop;
End;
