DECLARE
    A_   VARCHAR2(32000) := 'INFO'
                             || Chr(31)
                             || 'The calculated lead time for part 20-70018P is 50 days. Receipt date 10-JAN-19 requires a shorter delivery lead time. The earliest possible receipt date based on the calculated lead time is 01-MAR-19. Consider reviewing the receipt date. '
                             || Chr(30); --p0
    B_   VARCHAR2(32000) := NULL; --p1
    C_   VARCHAR2(32000) := NULL; --p2
    D_   VARCHAR2(32000) := 'ORDER_NO'
                             || Chr(31)
                             || 'P19128'
                             || Chr(30)
                             || 'VENDOR_NO'
                             || Chr(31)
                             || '54869'
                             || Chr(30)
                             || 'CURRENCY_CODE'
                             || Chr(31)
                             || 'USD'
                             || Chr(30)
                             || 'COMPANY'
                             || Chr(31)
                             || '100'
                             || Chr(30)
                             || 'CURRENCY_RATE'
                             || Chr(31)
                             || '1'
                             || Chr(30)
                             || 'PART_NO'
                             || Chr(31)
                             || '20-70018P'
                             || Chr(30)
                             || 'DESCRIPTION'
                             || Chr(31)
                             || 'Int Hex Adv Plus Imp NP 3.25x10'
                             || Chr(30)
                             || 'BUY_QTY_DUE'
                             || Chr(31)
                             || '70'
                             || Chr(30)
                             || 'BUY_UNIT_MEAS'
                             || Chr(31)
                             || 'EA'
                             || Chr(30)
                             || 'PLANNED_RECEIPT_DATE'
                             || Chr(31)
                             || '2019-01-10-00.00.00'
                             || Chr(30)
                             || 'PLANNED_DELIVERY_DATE'
                             || Chr(31)
                             || '2019-01-10-00.00.00'
                             || Chr(30)
                             || 'WANTED_DELIVERY_DATE'
                             || Chr(31)
                             || '2019-01-10-00.00.00'
                             || Chr(30)
                             || 'PROMISED_DELIVERY_DATE'
                             || Chr(31)
                             || '2019-01-10-00.00.00'
                             || Chr(30)
                             || 'FBUY_UNIT_PRICE'
                             || Chr(31)
                             || '30'
                             || Chr(30)
                             || 'PRICE_UNIT_MEAS'
                             || Chr(31)
                             || 'EA'
                             || Chr(30)
                             || 'BUY_UNIT_PRICE'
                             || Chr(31)
                             || '30'
                             || Chr(30)
                             || 'PRICE_CONV_FACTOR'
                             || Chr(31)
                             || '1'
                             || Chr(30)
                             || 'DISCOUNT'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'ADDITIONAL_COST_AMOUNT'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'TAX_EXEMPT_DB'
                             || Chr(31)
                             || 'TRUE'
                             || Chr(30)
                             || 'TAXABLE_DB'
                             || Chr(31)
                             || 'FALSE'
                             || Chr(30)
                             || 'FEE_CODE'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'TAX_SHIP_ADDRESS'
                             || Chr(31)
                             || 'Ship-to'
                             || Chr(30)
                             || 'AUTOMATIC_INVOICE_DB'
                             || Chr(31)
                             || 'MANUAL'
                             || Chr(30)
                             || 'INVOICING_SUPPLIER'
                             || Chr(31)
                             || '54869'
                             || Chr(30)
                             || 'BLANKET_ORDER'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'BLANKET_LINE'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'PURCHASE_PAYMENT_TYPE'
                             || Chr(31)
                             || 'Normal'
                             || Chr(30)
                             || 'PAY_TAX_DB'
                             || Chr(31)
                             || 'FALSE'
                             || Chr(30)
                             || 'CLOSE_CODE'
                             || Chr(31)
                             || 'Automatic'
                             || Chr(30)
                             || 'CLOSE_TOLERANCE'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'RECEIVE_CASE'
                             || Chr(31)
                             || 'Receive into Inventory'
                             || Chr(30)
                             || 'INSPECTION_CODE'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'INTERNAL_CONTROL_TIME'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'SAMPLE_PERCENT'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'SAMPLE_QTY'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'QC_CODE'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'ORD_CONF_REMINDER'
                             || Chr(31)
                             || 'No Order Reminder'
                             || Chr(30)
                             || 'ORD_CONF_REM_NUM'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'DELIVERY_REMINDER'
                             || Chr(31)
                             || 'No Delivery Reminder'
                             || Chr(30)
                             || 'DELIVERY_REM_NUM'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'CONTRACT'
                             || Chr(31)
                             || '100'
                             || Chr(30)
                             || 'DEFAULT_ADDR_FLAG_DB'
                             || Chr(31)
                             || 'Y'
                             || Chr(30)
                             || 'ADDRESS_ID'
                             || Chr(31)
                             || '05'
                             || Chr(30)
                             || 'ADDR_FLAG_DB'
                             || Chr(31)
                             || 'N'
                             || Chr(30)
                             || 'UNIT_MEAS'
                             || Chr(31)
                             || 'EA'
                             || Chr(30)
                             || 'PROCESS_TYPE'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'MANUFACTURER_ID'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'MANUFACTURER_PART_NO'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'IS_EXCHANGE_PART'
                             || Chr(31)
                             || 'FALSE'
                             || Chr(30)
                             || 'EXCHANGE_ITEM_DB'
                             || Chr(31)
                             || 'ITEM NOT EXCHANGED'
                             || Chr(30)
                             || 'QTY_SCRAPPED_SUPPLIER'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'WARRANTY_ID'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'PURCHASE_SITE'
                             || Chr(31)
                             || '100'
                             || Chr(30)
                             || 'INTRASTAT_AFFECTED_DB'
                             || Chr(31)
                             || 'FALSE'
                             || Chr(30)
                             || 'CUSTOMS_STAT_NO'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'FBUY_UNIT_PRICE'
                             || Chr(31)
                             || '30'
                             || Chr(30)
                             || 'DATE_TYPE'
                             || Chr(31)
                             || 'PLANNED_RECEIPT_DATE'
                             || Chr(30)
                             || 'TAX_AMOUNT'
                             || Chr(31)
                             || '0'
                             || Chr(30); --p3
    E_   VARCHAR2(32000) := 'DO'; --p4
BEGIN
    For Parts In (Select Price_List_No, Catalog_No  From KD_Price_List_Upload)
    Loop
        A_:= NULL;
        B_:= NULL;
        C_:= NULL;
        D_:= 'ORDER_NO'
                             || Chr(31)
                             || 'P19128'
                             || Chr(30)
                             || 'VENDOR_NO'
                             || Chr(31)
                             || '54869'
                             || Chr(30)
                             || 'CURRENCY_CODE'
                             || Chr(31)
                             || 'USD'
                             || Chr(30)
                             || 'COMPANY'
                             || Chr(31)
                             || '100'
                             || Chr(30)
                             || 'CURRENCY_RATE'
                             || Chr(31)
                             || '1'
                             || Chr(30)
                             || 'PART_NO'
                             || Chr(31)
                             || Parts.Price_List_No
                             || Chr(30)
                             || 'DESCRIPTION'
                             || Chr(31)
                             || Inventory_Part_Api.Get_Description('100',Parts.Price_List_No)
                             || Chr(30)
                             || 'BUY_QTY_DUE'
                             || Chr(31)
                             || Parts.Catalog_No
                             || Chr(30)
                             || 'BUY_UNIT_MEAS'
                             || Chr(31)
                             || 'EA'
                             || Chr(30)
                             || 'PLANNED_RECEIPT_DATE'
                             || Chr(31)
                             || '2019-01-18-00.00.00'
                             || Chr(30)
                             || 'PLANNED_DELIVERY_DATE'
                             || Chr(31)
                             || '2019-01-18-00.00.00'
                             || Chr(30)
                             || 'WANTED_DELIVERY_DATE'
                             || Chr(31)
                             || '2019-01-18-00.00.00'
                             || Chr(30)
                             || 'PROMISED_DELIVERY_DATE'
                             || Chr(31)
                             || '2019-01-18-00.00.00'
                             || Chr(30)
                             || 'FBUY_UNIT_PRICE'
                             || Chr(31)
                             || Purchase_Part_Supplier_Api.Get_List_Price('100',Parts.Price_List_No,'54869')
                             || Chr(30)
                             || 'PRICE_UNIT_MEAS'
                             || Chr(31)
                             || 'EA'
                             || Chr(30)
                             || 'BUY_UNIT_PRICE'
                             || Chr(31)
                             || Purchase_Part_Supplier_Api.Get_List_Price('100',Parts.Price_List_No,'54869')
                             || Chr(30)
                             || 'PRICE_CONV_FACTOR'
                             || Chr(31)
                             || '1'
                             || Chr(30)
                             || 'DISCOUNT'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'ADDITIONAL_COST_AMOUNT'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'TAX_EXEMPT_DB'
                             || Chr(31)
                             || 'TRUE'
                             || Chr(30)
                             || 'TAXABLE_DB'
                             || Chr(31)
                             || 'FALSE'
                             || Chr(30)
                             || 'FEE_CODE'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'TAX_SHIP_ADDRESS'
                             || Chr(31)
                             || 'Ship-to'
                             || Chr(30)
                             || 'AUTOMATIC_INVOICE_DB'
                             || Chr(31)
                             || 'MANUAL'
                             || Chr(30)
                             || 'INVOICING_SUPPLIER'
                             || Chr(31)
                             || '54869'
                             || Chr(30)
                             || 'BLANKET_ORDER'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'BLANKET_LINE'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'PURCHASE_PAYMENT_TYPE'
                             || Chr(31)
                             || 'Normal'
                             || Chr(30)
                             || 'PAY_TAX_DB'
                             || Chr(31)
                             || 'FALSE'
                             || Chr(30)
                             || 'CLOSE_CODE'
                             || Chr(31)
                             || 'Automatic'
                             || Chr(30)
                             || 'CLOSE_TOLERANCE'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'RECEIVE_CASE'
                             || Chr(31)
                             || 'Receive into Inventory'
                             || Chr(30)
                             || 'INSPECTION_CODE'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'INTERNAL_CONTROL_TIME'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'SAMPLE_PERCENT'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'SAMPLE_QTY'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'QC_CODE'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'ORD_CONF_REMINDER'
                             || Chr(31)
                             || 'No Order Reminder'
                             || Chr(30)
                             || 'ORD_CONF_REM_NUM'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'DELIVERY_REMINDER'
                             || Chr(31)
                             || 'No Delivery Reminder'
                             || Chr(30)
                             || 'DELIVERY_REM_NUM'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'CONTRACT'
                             || Chr(31)
                             || '100'
                             || Chr(30)
                             || 'DEFAULT_ADDR_FLAG_DB'
                             || Chr(31)
                             || 'Y'
                             || Chr(30)
                             || 'ADDRESS_ID'
                             || Chr(31)
                             || '05'
                             || Chr(30)
                             || 'ADDR_FLAG_DB'
                             || Chr(31)
                             || 'N'
                             || Chr(30)
                             || 'UNIT_MEAS'
                             || Chr(31)
                             || 'EA'
                             || Chr(30)
                             || 'PROCESS_TYPE'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'MANUFACTURER_ID'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'MANUFACTURER_PART_NO'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'IS_EXCHANGE_PART'
                             || Chr(31)
                             || 'FALSE'
                             || Chr(30)
                             || 'EXCHANGE_ITEM_DB'
                             || Chr(31)
                             || 'ITEM NOT EXCHANGED'
                             || Chr(30)
                             || 'QTY_SCRAPPED_SUPPLIER'
                             || Chr(31)
                             || '0'
                             || Chr(30)
                             || 'WARRANTY_ID'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'PURCHASE_SITE'
                             || Chr(31)
                             || '100'
                             || Chr(30)
                             || 'INTRASTAT_AFFECTED_DB'
                             || Chr(31)
                             || 'FALSE'
                             || Chr(30)
                             || 'CUSTOMS_STAT_NO'
                             || Chr(31)
                             || ''
                             || Chr(30)
                             || 'FBUY_UNIT_PRICE'
                             || Chr(31)
                             || Purchase_Part_Supplier_Api.Get_List_Price('100',Parts.Price_List_No,'54869')
                             || Chr(30)
                             || 'DATE_TYPE'
                             || Chr(31)
                             || 'PLANNED_RECEIPT_DATE'
                             || Chr(30)
                             || 'TAX_AMOUNT'
                             || Chr(31)
                             || '0'
                             || Chr(30); --p3
        E_:= 'DO';
        Ifsapp.Purchase_Order_Line_Part_Api.New__(A_,B_,C_,D_,E_);
    End Loop;
END;